server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/h5jingbiao?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.dy.h5jingbiao.entity

beetl-beetlsql.dev: true